spring:
  config:
    name: dt-customers-service
    import: app-config/common.yml
  profiles:
    group:
      vpn: local,local-vpn
    active: local
---
spring:
  config:
    activate:
      on-profile: local
    import: app-config/application-local.yml

---
spring:
  config:
    activate:
      on-profile: local-vpn
    import: app-config/application-local-vpn.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import: /etc/config/dt-customers-service-dev.properties

---
spring:
  config:
    activate:
      on-profile: uat
    import: /etc/config/dt-customers-service-uat.yml