spring:
  config:
    name: theatre-service
    import: app-config/common.yml
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
    import: app-config/application-local.yml
